### ISSUE TITLE
Check improper format for updating the DOW of office hours

### ISSUE THREAD

**Issue by rsdexter** [SamR71/Office-Hours#75]
Currently, we only support the format for the days of the week in the updating office hours fields to be in some form similar to "MWRF", where
M - monday
T - Tuesday
W - Wednesday
R - Thursday
F - Friday
S - Saturday
and any other character represents Sunday.

We should check that the user inputs the dates in a normal format to prevent issues such as updating the date to be "Friday". Inputting something like "Friday" would cause the office hours to occur once on Friday for "F", and 5 times on sunday for "r" - "y".

Users should be notified if their input does not follow an acceptable format.

**Comment by rsdexter** [comment]
The users should only be able to enter MTWRFSU, where the above mappings are the same except "U" correlates to sunday.

**Comment by rsdexter** [comment]
Also days should only be able to appear once. For example "MM" should no longer put two meetings on monday during the same time.

**Comment by kirm99** [comment]
We should eventually have a drop-down where the instructor chooses the days of the week to avoid bugs while using.

**Comment by venkatrsrinivas** [comment]
Currently implemented so that Modal Window details format of the dates parameter (i.e., Only MTWRFSU).
Further, made it so that the client/user is notified if they enter any character for dates that are not invalid or if they enter any date multiple times. 
But yes, I agree with Kirsten that we should eventually make it so that there is a Drop Down to avoid any unnecessary error checking of the input from our end.
